# Pipeline Terraform
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#

name: 'ansible-test'

env:
  environment: 'dev'

on: 
  workflow_dispatch:
    inputs:
      action:
        description: 'Parametro de prueba'     
        required: true
        default: 'check' 
        type: choice
        options:
        - start
        - stop
        - check 
#on:
#  push:
#    branches:
#      - terraform-v1
#    paths:
#      - '.github/workflows/locks.yml'

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python 
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Ansible
      run: |
        python -m pip install ansible
        ansible --version
    
    - name: Run test Playbook
      run: ansible-playbook ./ansible/hola.yml

    - name: Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: 2.36.0

    - name: Install Azure Collection
      run: |
        ansible-galaxy collection install azure.azcollection --force
        pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
    
    - name: Run test Azure
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      run: ansible-playbook ./ansible/TestAzureInfo.yml
