# Pipeline Terraform
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#

name: 'ansible-test'

env:
  environment: 'dev'

on: 
  workflow_dispatch:
    inputs:
      action:
        description: 'Parametro de prueba'     
        required: true
        default: 'check' 
        type: choice
        options:
        - start
        - stop
        - check 
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       ref: 'terraform-v1'
    
    - name: Setup Python 
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Ansible
      run: |
        python -m pip install ansible
        ansible --version
    
    - name: Run test Playbook
      env:
          PARAM: ${{ github.event.inputs.action }}
      run: ansible-playbook ./ansible/hola.yml -e PARAM=$PARAM

    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Install Azure Collection
      run: |
        ansible-galaxy collection install azure.azcollection --force
        pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
    
    #- name: Export environment variables
    #  env:
    #    AZURE_CLIENT_ID: IDddddddddddddddd
    #    AZURE_SECRET: xxxxxxxxxxxxxxxxxxxxxx
    #    AZURE_TENANT: T_IDddddddddddddd
    #    AZURE_SUBSCRIPTION_ID: S_IDddddddddddddddd
    #  run: |
    #    echo "AZURE_CLIENT_ID=$AZURE_CLIENT_ID" >> $GITHUB_ENV
    #    echo "AZURE_SECRET=$AZURE_SECRET" >> $GITHUB_ENV
    #    echo "AZURE_TENANT=$AZURE_TENANT" >> $GITHUB_ENV
    #    echo "AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID" >> $GITHUB_ENV
    #  
    #- name: Debug
    #  run: |
    #    env
    #    echo "${{ env.AZURE_CLIENT_ID }}" 
    
    - name: Run test Azure
      env:
        AZURE_CLIENT_ID: IDddddddddddddddd
        AZURE_SECRET: xxxxxxxxxxxxxxxxxxxxxx
        AZURE_TENANT: T_IDdddddddddddddRRRRRRRRRRRRRRRRR
        AZURE_SUBSCRIPTION_ID: S_IDddddddddddddddd
      run: ansible-playbook ./ansible/TestAzureInfo.yml
